### ISSUE TITLE
Popup window opens in the middle of a screen on Wayland

### ISSUE THREAD

**Issue by gudvinr** [Martchus/syncthingtray#170] opened 2023-01-03 11:57 UTC
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* Versions of `syncthingtray`, `qtutilities` and `c++utilities`: 1.3.2, 6.10.0, 5.20.0
* Qt version: 5.15.7
* C++ compiler (name and version): gcc 12.2.0
* C++ standard library (name and version): whatever comes with gcc 12.2.0 I guess
* Operating system (name and version): Arch Linux

**Bug description**
I use tray version of syncthingtray under KDE Plasma 5.26.4 (Wayland).  
When I click on tray icon, popup window appears in the middle of a screen.

**Steps to reproduce**
1. Start tray app
2. Click on tray icon

**Expected behavior**
Popup window appears around tray area

**Screenshots**

**Additional context**

**Comment by Martchus** [comment] 2023-01-03 12:52
The lack of an API to allow applications to position themselves via absolute coordinates is not a bug but a "feature" of Wayland. There is no hope to circumvent this limitation anytime soon.

Note that I've already been trying to workaround the problem, see https://github.com/Martchus/syncthingtray/issues/157#issuecomment-1328249723 and subsequent comments. It is basically not possible/wanted.

So I must close this issue. I personally also find it quite sad to see the GNU/Linux desktop declining with Wayland, see https://github.com/Martchus/syncthingtray/issues/157#issuecomment-1331911395. However, there's nothing I can do about it within the scope of this project.

**Closed by Martchus** 2023-01-03 12:52 UTC
Labels: feature  request

**Comment by gudvinr** [comment] 2023-01-03 13:10
Okay. Thanks for explanation.

I was trying to set up window rule in KDE and noticed that window type is not _popup_ but _normal_ even though Popup is chosen in settings.

**Comment by Martchus** [comment] 2023-01-03 13:24
I'm also seeing `windowType = NET::Normal` and `popupWindow = false` here regardless of the window type. Likely that's because the window is a top-level window.

**Comment by Martchus** [comment] 2023-09-28 11:02
After 14 years we might eventually be able to fix this on Wayland after all: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/247

It is still a draft and maybe won't be accepted. Even if it will be accepted it will likely take a long time until there's support for it in Qt. So I'm keeping this issue closed for now.

**Comment by gudvinr** [comment] 2023-09-28 13:55
https://github.com/ProtonMail/proton-bridge/issues/273

I reported similar issue for other Qt app on wayland, there could be something useful there

**Comment by Martchus** [comment] 2023-09-28 14:02
I had a brief look but it is hard to tell. It looks like a notification window was problematic here. So probably they have just switched to D-Bus-based notifications. That's something Syncthing Tray already does so there's no room for improvement here.

**Comment by Martchus** [comment] 2023-10-09 08:56
Looks like 247 won't be approved. Maybe https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/249 will be instead.

**Comment by handsomexdd1024** [comment] 2024-01-07 12:36
I must say I observed a strange behaviour: With syncthing tray settings window opened, tray popup will show at the corner; closing the settings window and clicking tray icon again and popup window still appears in the centre.

**Comment by Martchus** [comment] 2024-01-07 13:22
Really, just use the Plasmoid under Wayland.

I really cannot support every Wayland competitor, especially since Wayland decides to be the one special platform not supporting absolute positioning and reading mouse coordinates.

You can just let it show in a regular window or let it show the web UI directly for the "minimalist" experience Wayland's streamlining is supposedly trying to enforce here.
