### ISSUE TITLE
Build fails on arch linux 

### ISSUE THREAD

**Issue by sarpik** [Martchus/syncthingtray#36] opened 2019-07-09 20:06 UTC
I've used `yay`, I've used `makepkg --nocheck` - it still fails.

```console
Call Stack (most recent call first):
  /usr/lib64/cmake/KF5Package/KF5PackageConfig.cmake:55 (find_dependency)
  /usr/share/cmake-3.14/Modules/CMakeFindDependencyMacro.cmake:48 (find_package)
  /usr/lib64/cmake/KF5Plasma/KF5PlasmaConfig.cmake:53 (find_dependency)
  plasmoid/CMakeLists.txt:17 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/kipras/builds/syncthingtray/src/syncthingtray-0.9.1/CMakeFiles/CMakeOutput.log".
==> ERROR: A failure occurred in build().
    Aborting...
```

[CMakeOutput.log](https://github.com/Martchus/syncthingtray/files/3374711/CMakeOutput.log)

```sh
$ uname -a
Linux arch-usb 5.1.16-arch1-1-ARCH #1 SMP PREEMPT Wed Jul 3 20:23:07 UTC 2019 x86_64 GNU/Linux
```

Related: #1 #24 #35

**Comment by Martchus** [comment] 2019-07-10 08:35
Using `--nockeck` will not help here because it already fails during CMake configuration. The other issues you mention are different and hence not related.

What is the actual error? The output you've pasted only contains the call stack but not the actual error message and CMakeOutput.log contains only compiler checks. Since the error happens inside distribution provided CMake package files it might be a faulty package.

**Comment by sarpik** [comment] 2019-10-05 20:39
Hello,
the build is still failing.

How do I retrieve the "full error"?

**Comment by Martchus** [comment] 2019-10-05 21:22
I thought there would be an actual error message before the "Call Stack ..." line (within the normal build log).

Does it build when adding `-DNO_FILE_ITEM_ACTION_PLUGIN=ON` and `-DNO_PLASMOID=ON` to the CMake arguments? This would disable the KDE integration (and might help since the error occurs inside some KDE Frameworks CMake module).

But you're using Arch Linux, right? It generally works to build the package under that distribution. I do that all the time (with makechrootpkg or by just invoking CMake manually).

**Comment by Martchus** [comment] 2019-10-05 21:26
Note that I provide a custom repo as well: https://wiki.archlinux.org/index.php/Unofficial_user_repositories#ownstuff (the build is conducted with makechrootpkg like the official packages)

**Comment by sarpik** [comment] 2019-10-06 11:34
Yes, I'am indeed using arch linux.

It finally works after building from source! :tada: 

### My failed attempt (straight from docs without modifying):

```sh
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="/install/prefix" ./syncthingtray
make install -j$(nproc)
```

which failed.

### Successful attempt:

With your previously mentioned options `-DNO_FILE_ITEM_ACTION_PLUGIN=ON` and `-DNO_PLASMOID=ON` it worked!

Though I also needed to use `sudo` for `make install` (and I obviously changed the `-DCMAKE_INSTALL_PREFIX` to `/usr/local/bin`):

```sh
cmake -DNO_FILE_ITEM_ACTION_PLUGIN=ON -DNO_PLASMOID=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="/usr/local/bin" ./syncthingtray
sudo make install -j$(nproc)
```

and now it fully works!

I hope that this could be available by default, or maybe I have some strange stuff in my system which causes this behaviour - I don't know:D

---

Yep, there is a full error:

[syncthingerr.txt](https://github.com/Martchus/syncthingtray/files/3694272/syncthingerr.txt)

<details>
<summary>
Click to see
</summary>

```sh
[kipras@arch-usb turbo-schedule (master $% u+1)]$ yay -S syncthingtray                       
:: There are 2 providers available for syncthingtray:
:: Repository AUR
    1) syncthingtray 2) syncthingtray-git 

Enter a number (default=1): 
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur: 1]  syncthingtray-0.10.1-1

  1 syncthingtray                    (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> A
:: Deleting (1/1): /home/kipras/.cache/yay/syncthingtray
:: Downloaded PKGBUILD (1/1): syncthingtray
  1 syncthingtray                    (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: Parsing SRCINFO (1/1): syncthingtray
==> Making package: syncthingtray 0.10.1-1 (Sun 06 Oct 2019 02:15:52 PM EEST)
==> Retrieving sources...
  -> Downloading syncthingtray-0.10.1.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   131    0   131    0     0     60      0 --:--:--  0:00:02 --:--:--    60
100 1383k    0 1383k    0     0   383k      0 --:--:--  0:00:03 --:--:-- 1663k
==> Validating source files with sha256sums...
    syncthingtray-0.10.1.tar.gz ... Passed
==> Cleaning up...
==> Making package: syncthingtray 0.10.1-1 (Sun 06 Oct 2019 02:15:57 PM EEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found syncthingtray-0.10.1.tar.gz
==> Validating source files with sha256sums...
    syncthingtray-0.10.1.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting syncthingtray-0.10.1.tar.gz with bsdtar
==> Sources are ready.
==> Making package: syncthingtray 0.10.1-1 (Sun 06 Oct 2019 02:15:58 PM EEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- systemd support enabled
-- Configuring project syncthingconnector
-- Using default CXX11 ABI (not forcing old CX11 ABI).
-- For the check target to work, it is required to call enable_testing() on the source directory root.
CMake Warning at /usr/share/c++utilities/cmake/modules/BasicConfig.cmake:309 (message):
  Format rules for clang-format not found.
Call Stack (most recent call first):
  connector/CMakeLists.txt:120 (include)


-- Project has D-Bus interface declarations which will be processed.
-- Linking syncthingconnector against Qt 5 module Qt5::Network.
-- Linking syncthingconnector against Qt 5 module Qt5::Core.
-- Linking syncthingconnector against Qt 5 module Qt5::DBus.
-- qmake variable QT_INSTALL_TRANSLATIONS is /usr/share/qt/translations
-- Project has translations which will be released.
-- Using template for qtconfig.h from QT_UTILITIES installation.
-- Using template for global.h from CPP_UTILITIES installation.
-- Using template for version.h from CPP_UTILITIES installation.
-- Using template for Config.cmake from CPP_UTILITIES installation.
-- Using template for template.pc from CPP_UTILITIES installation.
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.6.3") 
-- Checking for one of the modules 'cppunit>=1.13.0'
-- Linking test target against syncthingconnector
-- Using template for doxygen from CPP_UTILITIES installation.
CMake Warning at /usr/share/c++utilities/cmake/modules/Doxygen.cmake:30 (message):
  Doxygen not found, unable to add target for generating API documentation
  for syncthingconnector
Call Stack (most recent call first):
  connector/CMakeLists.txt:129 (include)


-- Using template for config.h from CPP_UTILITIES installation.
-- Configuring project syncthingtesthelper
-- Using default CXX11 ABI (not forcing old CX11 ABI).
-- For the check target to work, it is required to call enable_testing() on the source directory root.
CMake Warning at /usr/share/c++utilities/cmake/modules/BasicConfig.cmake:309 (message):
  Format rules for clang-format not found.
Call Stack (most recent call first):
  testhelper/CMakeLists.txt:39 (include)


-- Linking syncthingtesthelper against Qt 5 module Qt5::Network.
-- Linking syncthingtesthelper against Qt 5 module Qt5::Core.
-- qmake variable QT_INSTALL_TRANSLATIONS is /usr/share/qt/translations
-- Using template for qtconfig.h from QT_UTILITIES installation.
-- Using template for global.h from CPP_UTILITIES installation.
-- Using template for version.h from CPP_UTILITIES installation.
-- Using template for Config.cmake from CPP_UTILITIES installation.
-- Using template for template.pc from CPP_UTILITIES installation.
-- Linking test target against syncthingtesthelper
-- Using template for doxygen from CPP_UTILITIES installation.
CMake Warning at /usr/share/c++utilities/cmake/modules/Doxygen.cmake:30 (message):
  Doxygen not found, unable to add target for generating API documentation
  for syncthingtesthelper
Call Stack (most recent call first):
  testhelper/CMakeLists.txt:44 (include)


-- Using template for config.h from CPP_UTILITIES installation.
-- Configuring project syncthingctl
-- Using default CXX11 ABI (not forcing old CX11 ABI).
-- For the check target to work, it is required to call enable_testing() on the source directory root.
CMake Warning at /usr/share/c++utilities/cmake/modules/BasicConfig.cmake:309 (message):
  Format rules for clang-format not found.
Call Stack (most recent call first):
  cli/CMakeLists.txt:33 (include)


-- Using Qt QML as JavaScript provider.
-- Using template for jsdefs.h from QT_UTILITIES installation.
-- Using template for jsincludes.h from QT_UTILITIES installation.
-- Linking syncthingctl against Qt 5 module Qt5::Qml.
-- Linking syncthingctl against Qt 5 module Qt5::Core.
-- qmake variable QT_INSTALL_TRANSLATIONS is /usr/share/qt/translations
-- Using template for qtconfig.h from QT_UTILITIES installation.
-- Using template for desktop from CPP_UTILITIES installation.
-- Using template for appdata.xml from CPP_UTILITIES installation.
-- Checking for one of the modules 'cppunit>=1.13.0'
-- Using template for bash-completion.sh from CPP_UTILITIES installation.
-- Generating files for bash completion.
-- Using template for doxygen from CPP_UTILITIES installation.
CMake Warning at /usr/share/c++utilities/cmake/modules/Doxygen.cmake:30 (message):
  Doxygen not found, unable to add target for generating API documentation
  for syncthingctl
Call Stack (most recent call first):
  cli/CMakeLists.txt:45 (include)


-- Using template for config.h from CPP_UTILITIES installation.
-- Configuring project syncthingmodel
-- Using default CXX11 ABI (not forcing old CX11 ABI).
-- For the check target to work, it is required to call enable_testing() on the source directory root.
CMake Warning at /usr/share/c++utilities/cmake/modules/BasicConfig.cmake:309 (message):
  Format rules for clang-format not found.
Call Stack (most recent call first):
  model/CMakeLists.txt:52 (include)


-- Linking syncthingmodel against Qt 5 module Qt5::Network.
-- Linking syncthingmodel against Qt 5 module Qt5::Gui.
-- Linking syncthingmodel against Qt 5 module Qt5::Widgets.
-- Linking syncthingmodel against Qt 5 module Qt5::Svg.
-- Linking syncthingmodel against Qt 5 module Qt5::Core.
-- qmake variable QT_INSTALL_TRANSLATIONS is /usr/share/qt/translations
-- Project has translations which will be released.
-- Using template for qtconfig.h from QT_UTILITIES installation.
-- Using template for global.h from CPP_UTILITIES installation.
-- Using template for version.h from CPP_UTILITIES installation.
-- Using template for Config.cmake from CPP_UTILITIES installation.
-- Using template for template.pc from CPP_UTILITIES installation.
-- Using template for doxygen from CPP_UTILITIES installation.
CMake Warning at /usr/share/c++utilities/cmake/modules/Doxygen.cmake:30 (message):
  Doxygen not found, unable to add target for generating API documentation
  for syncthingmodel
Call Stack (most recent call first):
  model/CMakeLists.txt:56 (include)


-- Using template for config.h from CPP_UTILITIES installation.
-- Configuring project syncthingwidgets
-- Using default CXX11 ABI (not forcing old CX11 ABI).
-- For the check target to work, it is required to call enable_testing() on the source directory root.
CMake Warning at /usr/share/c++utilities/cmake/modules/BasicConfig.cmake:309 (message):
  Format rules for clang-format not found.
Call Stack (most recent call first):
  widgets/CMakeLists.txt:108 (include)


-- Building with Qt Widgets GUI.
-- Building WITHOUT Qt Quick GUI.
-- Using Qt WebEngine as web view provider.
-- Using template for webviewdefs.h from QT_UTILITIES installation.
-- Using template for webviewincludes.h from QT_UTILITIES installation.
-- Linking syncthingwidgets against Qt 5 module Qt5::Network.
-- Linking syncthingwidgets against Qt 5 module Qt5::Concurrent.
-- Linking syncthingwidgets against Qt 5 module Qt5::Gui.
-- Linking syncthingwidgets against Qt 5 module Qt5::Widgets.
-- Linking syncthingwidgets against Qt 5 module Qt5::WebEngineWidgets.
-- Linking syncthingwidgets against Qt 5 module Qt5::Core.
-- qmake variable QT_INSTALL_TRANSLATIONS is /usr/share/qt/translations
-- Project has translations which will be released.
-- Using template for qtconfig.h from QT_UTILITIES installation.
-- Using template for global.h from CPP_UTILITIES installation.
-- Using template for version.h from CPP_UTILITIES installation.
-- Using template for Config.cmake from CPP_UTILITIES installation.
-- Using template for template.pc from CPP_UTILITIES installation.
-- Using template for doxygen from CPP_UTILITIES installation.
CMake Warning at /usr/share/c++utilities/cmake/modules/Doxygen.cmake:30 (message):
  Doxygen not found, unable to add target for generating API documentation
  for syncthingwidgets
Call Stack (most recent call first):
  widgets/CMakeLists.txt:114 (include)


-- Using template for config.h from CPP_UTILITIES installation.
-- Configuring project syncthingtray
-- Using default CXX11 ABI (not forcing old CX11 ABI).
-- For the check target to work, it is required to call enable_testing() on the source directory root.
CMake Warning at /usr/share/c++utilities/cmake/modules/BasicConfig.cmake:309 (message):
  Format rules for clang-format not found.
Call Stack (most recent call first):
  tray/CMakeLists.txt:108 (include)


-- Building with Qt Widgets GUI.
-- Building WITHOUT Qt Quick GUI.
-- Linking syncthingtray against Qt 5 module Qt5::Network.
-- Linking syncthingtray against Qt 5 module Qt5::Gui.
-- Linking syncthingtray against Qt 5 module Qt5::Widgets.
-- Linking syncthingtray against Qt 5 module Qt5::Core.
-- qmake variable QT_INSTALL_TRANSLATIONS is /usr/share/qt/translations
-- Project has translations which will be released.
-- Using template for qtconfig.h from QT_UTILITIES installation.
-- Using template for desktop from CPP_UTILITIES installation.
-- Using template for appdata.xml from CPP_UTILITIES installation.
-- Using template for bash-completion.sh from CPP_UTILITIES installation.
-- Generating files for bash completion.
-- Using template for doxygen from CPP_UTILITIES installation.
CMake Warning at /usr/share/c++utilities/cmake/modules/Doxygen.cmake:30 (message):
  Doxygen not found, unable to add target for generating API documentation
  for syncthingtray
Call Stack (most recent call first):
  tray/CMakeLists.txt:128 (include)


-- Using template for config.h from CPP_UTILITIES installation.
CMake Error at /usr/share/cmake-3.15/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  Could not find a configuration file for package "KF5CoreAddons" that is
  compatible with requested version "5.62.0".

  The following configuration files were considered but not accepted:

    /usr/lib64/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake, version: 5.58.0
    /usr/lib/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake, version: 5.58.0
    /lib64/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake, version: 5.58.0
    /lib/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake, version: 5.58.0

Call Stack (most recent call first):
  /usr/lib64/cmake/KF5Package/KF5PackageConfig.cmake:55 (find_dependency)
  /usr/share/cmake-3.15/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/lib64/cmake/KF5Plasma/KF5PlasmaConfig.cmake:53 (find_dependency)
  plasmoid/CMakeLists.txt:17 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/kipras/.cache/yay/syncthingtray/src/syncthingtray-0.10.1/CMakeFiles/CMakeOutput.log".
==> ERROR: A failure occurred in build().
    Aborting...
Error making: syncthingtray
[kipras@arch-usb turbo-schedule (master $% u+1)]$ 
```

</details>

**Comment by Martchus** [comment] 2019-10-06 12:36
You have inconsistent versions of the KDE libraries (or at least their CMake configuration files) installed. So this is indeed a problem on your side.

I don't want to make the configuration without KDE integration the default under GNU/Linux because I'd like distributors to ship the software with all its features (possibly using split packages).

I also don't like to propose people to install things under `/usr/local` because that directory will become a mess sooner or later. I'd rather install it in a *dedicated* sub directory within my home directory.

**Comment by sarpik** [comment] 2019-10-06 12:56
Alright. That's strange thought because I didn't do anything to mess with the library versions, not even the KDE libraries themselves.

Yeah, makes sense to allow KDE integration by default.

The `/usr/local` - yeah, I actually remembered I use `~/.local` instead - will re-install:D I guess it depends on what you want.

Thanks for your help, I suppose we can close this?

The only problem for me right now is that the settings aren't saved and syncthingtray prompts me everytime I re-launch it to "configure how to connect to syncthing when using for the first time", even though I've already done so.

**Comment by Martchus** [comment] 2019-10-06 15:31
Yes, I would close the issue. I briefly investigated the settings problem and I can indeed reproduce the following issue: https://github.com/Martchus/syncthingtray/issues/59

**Closed by Martchus** 2019-10-06 15:31 UTC
