### ISSUE TITLE
[Windows 10] Not connecting to Syncthing instance after boot

### ISSUE THREAD

**Issue by akuntsch** [Martchus/syncthingtray#13] opened 2018-01-18 12:33 UTC
I'm getting the following error after logging in to Windows after booting:

![error](https://user-images.githubusercontent.com/4771806/35098164-641d0aea-fc53-11e7-83ae-52831e1393f2.png)

My syncthingtray settings are as follows:

- Autostart enabled
- Syncthing launcher enabled with argument '-no-browser'
- Inotify-launcher disabled
- Poll interval for reconnect is 15000 ms

The autostart and syncthing launcher both work even with the Python error, but syncthingtray does not connect to the Syncthing instance automatically (I guess the reconnection only works if it was initially connected?).

**Comment by akuntsch** [comment] 2018-01-18 12:51
Nevermind the Python error. It was caused by SyncthingGTK which did not properly uninstall. 

The problem with syncthingtray not connecting to the Syncthing instance is still there though.

**Comment by Martchus** [comment] 2018-01-18 15:10
Mh... maybe Qt thinks that there's no internet connection available and then even prevents connecting to local host. So is there an internet connection?

And you really checked whether your Syncthing instance is reachable in general, eg. from web browser?

**Comment by akuntsch** [comment] 2018-01-18 15:34
Internet connection is available, Syncthing also reachable in a browser.

Hovering over the tray icon says 'Reconnecting...'. When I click the tray icon it shows this:

![tray](https://user-images.githubusercontent.com/4771806/35105711-a4e8bb8c-fc6c-11e7-9dba-481e522c6201.png)

Pressing the 'Connect' button there does not work either. 

![settings](https://user-images.githubusercontent.com/4771806/35105936-3178b660-fc6d-11e7-88fc-5645d324a9ae.png)

After pressing 'Apply connection settings ...' in the settings the connection is established and the tray works.

**Comment by Martchus** [comment] 2018-01-18 16:38
Ok. Not sure why it works via the Apply button in the settings and not elsewhere. Only explanation is that the settings haven't been applied before.

**Comment by akuntsch** [comment] 2018-01-18 16:55
They have been applied before. The settings also stick, so they are the same when I restart the program or reboot the PC.

**Comment by Martchus** [comment] 2018-01-23 09:56
I can not reproduce.

So when it does not connect, there's not even an error message shown?

As you tagged this with "[Windows 10]" specifically, I have to ask whether this issue only occurs under that platform? Or is it just the only platform you use?

**Comment by Martchus** [comment] 2018-05-01 20:39
I'm closing because you didn't reply anymore and so far I have not enough information to investigate this issue. Just reopen if you can provide more details (see my last comment).

**Closed** 2018-05-01 20:39 UTC
Labels: bug
