### ISSUE TITLE
SyncthingTray's built in web-view looks Pixelated.

### ISSUE THREAD

**Issue by KAGEYAM4** [Martchus/syncthingtray#219] opened 2023-12-14 09:36 UTC
**Environment and versions**
* Versions of `syncthingtray`, `qtutilities` and `c++utilities`: syncthengtray(Qt6) 1.4.10,
* Qt version: 6.6.1
* C++ compiler (name and version): …
* C++ standard library (name and version): …
* Operating system (name and version): Linux ArchLinux 6.6.6-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Mon, 11 Dec 2023 11:47:45 +0000 x86_64 GNU/Linux

**Bug description**
Syncthing WebView Text looks pixelated.

**Steps to reproduce**
1. …Right Click tray icon
2. …Open Syncthing

**Screenshots**
![image](https://github.com/Martchus/syncthingtray/assets/75798544/6a026251-308b-41d1-a3a4-4ca0c872bd36)
![image](https://github.com/Martchus/syncthingtray/assets/75798544/d4ee2592-21e5-47da-ad11-223df01b6c79)
![image](https://github.com/Martchus/syncthingtray/assets/75798544/79ecca37-df49-46c0-abe7-e2ce19bad61b)

**Additional context**
DE- Hyprland, with 1.25 scaling set.
Resolution : 1920x1080

**Comment by Martchus** [comment] 2023-12-14 11:14
I guess the upscaling behavior is simply the best you get in your specific graphical environment. This is not a bug and improving the behavior would be a feature request.

Note that this is a limitation of Qt (and maybe Qt WebEngine specifically) in combination with your graphical environment. So I'm sorry to say that you probably filed the issue at the wrong place. Likely Qt or Hyperland or both need improvement but I don't think I can do anything about it in Syncthing Tray itself.

So I'm closing this issue. If you believe I'm wrong and I in fact need to change code on my side (e.g. to disable legacy behavior of Qt explicitly) please point that out more directly. I will reopen the issue then.

As a workaround you can configure one of the other ways of opening the web interface.

I'd also like to note that this issue is likely under happening under Wayland-based environments. When I remember my testings under Windows correctly it worked fine there with 125 % scaling. That also speaks for the limitation not being on Syncthing Tray's side.

**Closed by Martchus** 2023-12-14 11:14 UTC
Labels: feature  request
