### ISSUE TITLE
Both standalone tray and plasmoid are visible in the system tray

### ISSUE THREAD

**Issue by sudhirkhanger** [Martchus/syncthingtray#278] opened 2024-08-24 07:29 UTC
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [x] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* Versions of `syncthingtray`, `qtutilities` and `c++utilities`: …, …, …
* Qt version: ….….…
* C++ compiler (name and version): …
* C++ standard library (name and version): …
* Operating system (name and version): …

```
syncthing/noble-updates,noble-security,now 1.27.2~ds4-1ubuntu0.24.04.1 amd64 [installed,automatic]
syncthingtray-kde-plasma/noble,now 1.4.12-1build2 amd64 [installed]
syncthingtray/noble,now 1.4.12-1build2 amd64 [installed,automatic]

Add any other context about the problem here.
Operating System: Kubuntu 24.04
KDE Plasma Version: 5.27.11
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.13
Kernel Version: 6.8.0-40-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-6820HQ CPU @ 2.70GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 530
Manufacturer: Dell Inc.
Product Name: Precision 5510
```

**Bug description**
There are two system tray icons

**Steps to reproduce**
1. …
2. …

**Expected behavior**
Only one system tray icon should be shown

**Screenshots**
![image](https://github.com/user-attachments/assets/64673237-aa10-41b0-b145-fd4893722366)

**Additional context**

**Comment by Martchus** [comment] 2024-08-24 08:47
Probably not a bug, please have a look at the following README section: https://github.com/Martchus/syncthingtray?tab=readme-ov-file#configuring-plasmoid

Without knowing how you configured the Plasmoid and/or the widgets based tray application I cannot provide further help.

**Comment by sudhirkhanger** [comment] 2024-08-24 17:06
Thanks the standalone system tray was removed when I moved the autostart file but now I have a different problem.

>[2024-08-24T22:35:05] Connection configuration is insufficient.

**Comment by Martchus** [comment] 2024-08-24 17:09
see https://github.com/Martchus/syncthingtray?tab=readme-ov-file#general-remarks-on-the-configuration

**Comment by Martchus** [comment] 2024-09-29 18:32
You can reopen this ticket if you need further help but I'll close it for now.

**Closed by Martchus** 2024-09-29 18:32 UTC
Labels: help wanted

**Comment by ossilator** [comment] 2024-09-30 07:14
the user-friendly thing to do would be an automatic detection of the situation (which should be trivial using the built-in dbus registration). a dialog would offer to disable one of the apps, or at least explain the options. expecting users to RTFM is so '90s ... :stuck_out_tongue_winking_eye:

**Comment by Martchus** [comment] 2024-09-30 08:01
Adding a note to the README is a task of 5 minutes and adds no complexity to the code I'll have to maintain in the future.

Adding extra IPC code and testing it is more work than you make it sound like and not trivial code. I am not going to spend the effort. Note that I develop this application only in my spare time. If you can provide a quick/trivial PR for this and can show that you've tested it, feel free to prove me wrong :-)

**Comment by sudhirkhanger** [comment] 2024-10-13 08:37
I just upgraded to Kubuntu 24.10 and the plasma widget disappeared. Syncthing is running in background but I can't find an option to enable plasma widget.

**Comment by Martchus** [comment] 2024-10-13 09:18
I cannot give support for downstream packaging. My guess is that the syncthingtray package you have installed doesn't use the same version of Qt than your plasmashell package. If that's the case you can either build syncthingtray yourself or use the standalone/widgets-based version.

**Comment by sudhirkhanger** [comment] 2024-10-13 09:29
```
Operating System: Kubuntu 24.10
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.6.0
Qt Version: 6.6.2
Kernel Version: 6.11.0-8-generic (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i7-6820HQ CPU @ 2.70GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 530
Manufacturer: Dell Inc.
Product Name: Precision 5510
```

Kubuntu 24.10 runs Qt version 6.6.2.

**Comment by Martchus** [comment] 2024-10-13 09:34
Ok, and I suspect your syncthingtray package still uses Qt 5. You may want to open a feature request on the issue tracker for this downstream packaging to bring those Qt versions in-line with each other.

**Comment by Martchus** [comment] 2024-10-14 21:18
@sudhirkhanger I've just got a bug report that contains information about packaging that could help you: https://github.com/Martchus/syncthingtray/issues/287
Although there might be the caveat of the built-in web view not working.
