### ISSUE TITLE
Submit Windows builds to Kaspersky's allowlist program

### ISSUE THREAD

**Issue by felikcat** [Martchus/syncthingtray#171] opened 2023-01-26 04:04 UTC
https://www.kaspersky.com/partners/allowlist-program

![librewolf_kNd9Xjnehb](https://user-images.githubusercontent.com/29991266/214756222-563763b4-b8d5-4fe7-9afc-ff00c6508bb4.png)

**Comment by Martchus** [comment] 2023-01-26 09:18
This is clearly not a bug on my side. I cannot take care of every anti virus scanner that I don't even use myself. Windows is a supported platform but dealing with software released by other people/organizations/companies is out of scope for this open source project.

**Closed by Martchus** 2023-01-26 09:18 UTC

**Comment by Martchus** [comment] 2023-01-26 09:20
Note that you're asking for something that wasn't done/supported before. So even if it was within the scope it would be a feature request and not a bug.

**Comment by felikcat** [comment] 2023-01-28 07:38
Clearly you don't know that anti-virus companies piggyback on each other if something is confirmed to be a false positive.

It's not in the scope of your project cause you're lazy.

**Comment by Martchus** [comment] 2023-01-28 11:05
It is not in the scope of my project because sometimes one has to say no. I cannot do everything everyone asks for in a spare time project.

Note that everyone, including you, is welcome to help. If you think it is important you can take care of it. This is how open source projects work.

(I suspect this doesn't even require a change in this repository's code - and if it would I would likely accept the contribution.)
