### ISSUE TITLE
buggy Appstream metadata

### ISSUE THREAD

**Issue by sten0** [Martchus/syncthingtray#296] opened 2024-11-13 13:01 UTC
I just finished building 1.6.3 for upload to Debian, and I built it with

cpp-utilities_5.26.1
qtutilities_6.14.3
qtforkawesome_0.2.0

unfortunately I can't upload it due to buggy appstream metadata
```
syncthingplasmoid.metainfo.xml
  I: io.github.martchus.syncthingplasmoid:45: unknown-tag developer
  W: io.github.martchus.syncthingplasmoid:~: metainfo-filename-cid-mismatch

syncthingfileitemaction.metainfo.xml
  I: io.github.martchus.syncthingfileitemaction:22: unknown-tag developer
  W: io.github.martchus.syncthingfileitemaction:~: metainfo-filename-cid-mismatch

syncthingtray.metainfo.xml
  I: io.github.martchus.syncthingtray:43: unknown-tag developer
  W: io.github.martchus.syncthingtray:~: metainfo-filename-cid-mismatch

✘ Validation failed: warnings: 3, infos: 3
```

**Comment by Martchus** [comment] 2024-11-13 13:37
Looks like there are just warnings but no errors. So these files are probably not "buggy" per-se. I've just run a local test run in verbose mode so you see the invoked commands and couldn't reproduce the problem:

```
$ ctest --verbose -R '.*appstream.*'
UpdateCTestConfiguration  from :/hdd/build/presets/syncthingtray/debug-qt6/DartConfiguration.tcl
UpdateCTestConfiguration  from :/hdd/build/presets/syncthingtray/debug-qt6/DartConfiguration.tcl
Test project /hdd/build/presets/syncthingtray/debug-qt6
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 24
    Start 24: syncthingtray-devel_appstream_validation

24: Test command: /usr/bin/appstreamcli "validate" "/hdd/build/presets/syncthingtray/debug-qt6/syncthingtray/tray/resources/syncthingtray-devel.metainfo.xml"
24: Working Directory: /hdd/build/presets/syncthingtray/debug-qt6/syncthingtray/tray
24: Test timeout computed to be: 10000000
24: ✔ Validierung war erfolgreich.
1/3 Test #24: syncthingtray-devel_appstream_validation .............   Passed    0.85 sec
test 26
    Start 26: syncthingplasmoid-devel_appstream_validation

26: Test command: /usr/bin/appstreamcli "validate" "/hdd/build/presets/syncthingtray/debug-qt6/syncthingtray/plasmoid/lib/resources/syncthingplasmoid-devel.metainfo.xml"
26: Working Directory: /hdd/build/presets/syncthingtray/debug-qt6/syncthingtray/plasmoid/lib
26: Test timeout computed to be: 10000000
26: I: io.github.martchus.syncthingplasmoid-devel:45: developer-id-missing
26: 
26: ✔ Validierung war erfolgreich: Informationen: 1
2/3 Test #26: syncthingplasmoid-devel_appstream_validation .........   Passed    0.67 sec
test 28
    Start 28: syncthingfileitemaction-devel_appstream_validation

28: Test command: /usr/bin/appstreamcli "validate" "/hdd/build/presets/syncthingtray/debug-qt6/syncthingtray/fileitemactionplugin/resources/syncthingfileitemaction-devel.metainfo.xml"
28: Working Directory: /hdd/build/presets/syncthingtray/debug-qt6/syncthingtray/fileitemactionplugin
28: Test timeout computed to be: 10000000
28: I: io.github.martchus.syncthingfileitemaction-devel:22: developer-id-missing
28: 
28: ✔ Validierung war erfolgreich: Informationen: 1
3/3 Test #28: syncthingfileitemaction-devel_appstream_validation ...   Passed    0.37 sec

The following tests passed:
        syncthingtray-devel_appstream_validation
        syncthingplasmoid-devel_appstream_validation
        syncthingfileitemaction-devel_appstream_validation

100% tests passed, 0 tests failed out of 3

Total Test time (real) =   1.90 sec
```

How did you invoke the validation and how do the XML files actually look like in your case?

Note that there might indeed be a regression because I changed this a little bit a while ago for the sake of making the Flatpak build easier. What version of Syncthing Tray was the last good one?

**Comment by Martchus** [comment] 2024-11-13 13:46
Note that you can use the `…_RDNS_OVERRIDE` and `…_DEVELOPER_ID_OVERRIDE` variables to override `<id>` and `<developer id="…">` in case changing these for the sake of the Flatpak caused a mismatch for existing packaging like yours. I remember people (who know and care more about this AppStream stuff than me) were against my build system allowing those overrides - so use them at your own risk :-)

**Comment by Martchus** [comment] 2024-11-13 13:52
By the way, 1.6.3 isn't the best release as the "Downloads" tab is completely broken. (Not that the it would really matter much.) So maybe it isn't the worst to wait for 1.6.4.

**Comment by sten0** [comment] 2024-11-13 15:01
Martchus ***@***.***> writes:

> Looks like there are just warnings but no errors. So these files are
> probably not "buggy" per-se.

Flathub and Debian both elevate metainfo-filename-cid-mismatch to an
error.  This needs to be fixed.

> How did you invoke the validation and how do the XML files actually look like in your case?

Build package and install/stage it to an fsroot.  Then cd to that location and
```
appstreamcli validate-tree ./
```

It's reproducible with Appstream 0.16.1 and 1.0.3.

> Note that there might indeed be a regression because I changed this a little bit a while ago for the sake of making the Flatpak build easier. What version of Syncthing Tray was the last good one?

1.5.4 was good.

**Comment by sten0** [comment] 2024-11-13 15:04
Martchus ***@***.***> writes:

> By the way, 1.6.3 isn't the best release as the "Downloads" tab is completely broken. (Not that the it would really matter much.) So maybe it isn't the worst to wait for 1.6.4.

Thanks for the notice, yes, I'll definitely wait, and please fix the
Appstream metadata in 1.6.4.

**Comment by Martchus** [comment] 2024-11-13 15:17
> Flathub and Debian both elevate metainfo-filename-cid-mismatch to an
> error.  This needs to be fixed.

The package was successfully updated to 1.6.3 on Flathub, see https://flathub.org/apps/io.github.martchus.syncthingtray. So I think whatever AppStream meta-data is generated by Syncthing Tray's build system generally works on Flathub.

Maybe the mismatch you see is actually *due* to changes I make for Flathub. Without knowing what expected value and actual value are the mismatch is hard to fix from my side. So maybe just use the overrides as mentioned to change the AppStream file to whatever you need in your case.

> Build package and install/stage it to an fsroot.  Then cd to that location and

This is very unspecific; probably you want me to follow a workflow using Debian-specific tooling. I don't think I want to do this right now.

If you need any Debian-specific changes to be done either state the concrete changes or create a PR yourself. Of course I now need to consider those changes won't break the Flatpak.

**Comment by sten0** [comment] 2024-11-13 16:01
Martchus ***@***.***> writes:

>> Flathub and Debian both elevate metainfo-filename-cid-mismatch to an
>> error.  This needs to be fixed.
>
> The package was successfully updated to 1.6.3 on Flathub, see https://flathub.org/apps/io.github.martchus.syncthingtray. So I think whatever AppStream meta-data is generated by Syncthing Tray's build system generally works on Flathub.
>
> Maybe the mismatch you see is actually *due* to changes I make for
> Flathub.

That's plausible.

> Without knowing what expected value and actual value are the mismatch is hard to fix from my side. So maybe just use the overrides as mentioned to change the AppStream file to whatever you need in your case.

Sorry, this isn't an acceptable option.  Appstream exists for universal
metadata and this must be identical across all distributed flatpaks,
appimages, rpms, debs, pkg.tar (Arch and its derivatives), etc.

>> Build package and install/stage it to an fsroot.  Then cd to that location and
>
> This is very unspecific; probably you want me to follow a workflow using Debian-specific tooling. I don't think I want to do this right now.

Do you consider the following Debian-specific?

make DESTDIR=/foo/dir install
cd /foo/dir
validate the tree with appstreamcli

> If you need any Debian-specific changes to be done either state the concrete changes or create a PR yourself. Of course I now need to consider those changes won't break the Flatpak.

I think you know very well that none of this is Debian-specific.  Is the
Flathub metadata what you intend to be Vorta's canonical metadata?  If
so, please provide me with a copy of the appstream file you distribute
on Flathub and we'll move forward from there.

**Comment by Martchus** [comment] 2024-11-13 16:31
> Sorry, this isn't an acceptable option.  Appstream exists for universal
> metadata and this must be identical across all distributed flatpaks,
> appimages, rpms, debs, pkg.tar (Arch and its derivatives), etc.

Ok, then we need to find out the expected and actual values of that check to come up with some change.

> Do you consider the following Debian-specific?

No - that's basically what I've already did, see my first response. I've now tried to use the `validate-tree` sub-command (which is probably the CLI option you're referring). (My approach with ctest is validating files individually which might make a difference.) However, this doesn't seem to work as it doesn't recursively check for relevant files:

```
appstreamcli validate-tree .

  I: ~:~: dir-no-metadata-found

✔ Validierung war erfolgreich: Informationen: 1
```

> I think you know very well that none of this is Debian-specific.  Is the
> Flathub metadata what you intend to be Vorta's canonical metadata?  If
> so, please provide me with a copy of the appstream file you distribute
> on Flathub and we'll move forward from there.

I just see that it works on Flathub but apparently not on Debian so that makes it *look* Debian-specific.

In my opinion it is ok for you to change the metadata or any aspect of this software in the way you like. After all, this is an open source project and you can apply patches as you like and then also re-distribute the whole thing (as long as the license is not violated). Maybe just don't call it Syncthing Tray anymore if you go too far :-)

However, if you want something canonical, then I'd say whatever my build system currently produces (without using any overrides or special prefix/suffix variables) can be considered official, e.g. checkout the metainfo in my [official generic GNU/Linux builds]([syncthingtray-1.6.3](https://martchus.dyn.f3l.de/repo/arch/ownstuff/os/x86_64/static-compat-syncthingtray-1.6.3-1-x86_64.pkg.tar.zst.sig). The Flatpak package contains presumably identical meta-data but I'm not sure how to check the Flatpak package contents. These builds don't contain the fileitemaction and plasmoid, though (for technical reasons). However, you can probably guess what the problematic meta-data fields of those components would be.

**Comment by sten0** [comment] 2024-11-13 19:02
Martchus ***@***.***> writes:

>> Sorry, this isn't an acceptable option.  Appstream exists for universal
>> metadata and this must be identical across all distributed flatpaks,
>> appimages, rpms, debs, pkg.tar (Arch and its derivatives), etc.
>
> Ok, then we need to find out the expected and actual values of that check to come up with some change.

Exactly :)

>> Do you consider the following Debian-specific?
>>
>> make DESTDIR=/foo/dir install
>
> No - that's basically what I've already did, see my first
> response. I've now tried to use the `validate-tree` sub-command (which
> is probably the CLI option you're referring). (My approach with ctest
> is validating files individually which might make a difference.)

Ah, yes, it definitely makes a difference.  Validate-tree also checks
for cohesiveness and compatibility and is thus more strict.

> However, this doesn't seem to work as it doesn't recursively check for relevant files:
>
> ```
> appstreamcli validate-tree .
>
>   I: ~:~: dir-no-metadata-found
>
> ✔ Validierung war erfolgreich: Informationen: 1
> ```

Hm, that's odd, because appstreamcli must necessarily recurse to
match both the appstream xml file and the desktop file (they're in
different directories in the same prefix), validate them individually,
then validate their congruence.  Do you have a
DESTDIR/usr/bin/syncthingtray, where it looks like DESTDIR=./ ?

> However, if you want something canonical, then I'd say whatever my build system currently produces (without using any overrides or special prefix/suffix variables) can be considered official, e.g. checkout the metainfo in my [official generic GNU/Linux builds]([syncthingtray-1.6.3](https://martchus.dyn.f3l.de/repo/arch/ownstuff/os/x86_64/static-compat-syncthingtray-1.6.3-1-x86_64.pkg.tar.zst.sig). The Flatpak package contains presumably identical meta-data but I'm not sure how to check the Flatpak package contents. These builds don't contain the fileitemaction and plasmoid, though (for technical reasons). However, you can probably guess what the problematic meta-data fields of those components would be.
>

I don't use Flatpak, but this should do the trick:

```
find /var/lib/flatpak | grep xml
find ~/.local/share/flatpak/ | grep xml
```

then attach the syncthingtray-related files here (or link to them).

As for your static package, here's a reproducer:

```
mkdir ~/appdata
cd ~/appdata
curl
https://martchus.dyn.f3l.de/repo/arch/ownstuff/os/x86_64/static-compat-syncthingtray-1.6.3-1-x86_64.pkg.tar.zst | tar --zstd -x -f -
appstreamcli validate-tree ./
```

returns

```
  I: ~:~: dir-no-metadata-found
```

because appstreamcli doesn't [yet] support /usr/static-compat/.  I
imagine upstream appstream would appreciate knowing about this
limitation.

A kludge for appstreamcli purposes:
```
cd usr/static-compat
cp -ari * ../share
```

Now `appstreamcli validate-tree ./` returns
```
syncthingtray.metainfo.xml
  I: io.github.martchus.syncthingtray:43: unknown-tag developer
  W: io.github.martchus.syncthingtray:~: metainfo-filename-cid-mismatch

✘ Validation failed: warnings: 1, infos: 1
```

Please send me the flatpak metainfo.xml so I can confirm that my
solution will work everywhere.

**Comment by sten0** [comment] 2024-11-13 19:07
Gah.

I meant this

A kludge for appstreamcli purposes:
```
cd usr/static-compat
cp -ari * ../
```

**Comment by Martchus** [comment] 2024-11-13 22:48
>because appstreamcli doesn't [yet] support /usr/static-compat/.

Oh, so this expects a certain file structure. Then it is no surprise that my previous tests didn't work. I guess I can test it again when I have time.

> Please send me the flatpak metainfo.xml so I can confirm that my
> solution will work everywhere.

I guess I also needed to download the [Flatpak](https://github.com/flathub/io.github.martchus.syncthingtray) first. (I'm not really using/developing the Flatpak myself.) I can do it when I have time.

---

And for further reference: https://freedesktop.org/software/appstream/docs/chap-Validation.html#asv-metainfo-filename-cid-mismatch

> The metainfo filename does not match the component ID.

**Comment by Martchus** [comment] 2024-11-15 21:43
I tested it again and I could now reproduce the warning. It looks like it really just didn't like that the file names aren't identical to the ID. I fixed that with a commit in c++utilities.

**Comment by Martchus** [comment] 2024-11-15 21:52
I was also able to get rid of the info message `developer-id-missing`.

I suppose you get `unknown-tag developer` because you're using an older version of `appstreamcli` which doesn't know the `developer` tag. I think you'll have to live with that info message until you update your version of `appstreamcli`.

With that everything seems fixed so I'm closing this issue.

**Closed by Martchus** 2024-11-15 21:52 UTC
Labels: bug
