### ISSUE TITLE
syncthingtray-1.4.3-x86_64-w64-mingw32-cli.exe flagged as Trojan (by 41 AV engines on VirusTotal !)

### ISSUE THREAD

**Issue by palijn** [Martchus/syncthingtray#193] opened 2023-07-04 15:26 UTC
Hi,
I just downloaded syncthingtray-1.4.3-x86_64-w64-mingw32-cli.exe (from the relevant .zip file in the Releases page).

My antivirus software insists in blocking/quarantining this file as being a Trojan.
As a matter of fact, uploading it to VirusTotal has it flagged as such by over 40 antivirus engines.

So, I'm wondering : is the downloadable executable clean, or has it been infected in some way ?

Another question is : the non-cli exe file seems clean. Is the -cli needed at all for the tray functionalities ?

Thanks for your support !

**Comment by Martchus** [comment] 2023-07-04 15:27
Not a bug of Syncthing Tray but a bug of your anti virus software. Closing as duplicate of #191.

**Closed by Martchus** 2023-07-04 15:27 UTC
Labels: bug

**Comment by palijn** [comment] 2023-07-04 15:30
Remaining question : Is the -cli needed at all for the tray functionalities ?

**Comment by Martchus** [comment] 2023-07-04 15:32
No - it is only required for using the command line interface in the Windows terminal.

**Comment by palijn** [comment] 2023-07-04 15:35
False Positive report submitted to BitDefender as of now.
(URL : https://www.bitdefender.com/consumer/support/answer/29358/ )

**Comment by Martchus** [comment] 2023-07-04 15:38
Ok, let's see whether it'll make any difference. I am going to release 1.4.4 soon so maybe that binary will be not detected anymore anyways.
