### ISSUE TITLE
Plasmoid icons too small on 4k display.

### ISSUE THREAD

**Issue by dontdieych** [Martchus/syncthingtray#71] opened 2020-07-17 19:00 UTC
**Relevant components**

* [* ] Plasmoid/applet for Plasma desktop

**Environment and versions**
Manjajro Linux

syncthingtray 0.11.1-1
qtutilities 6.2.0-1
c++utilities 5.5.0-1
qt5-base 5.15.0-3
qt5-svg 5.15.0-1
qt5-base 5.15.0-3

**Bug description**
I've set screen scale 250%. Other tray plasmoid's icons are proper size. Qtwidget version is ok.

**Screenshots**
qtwidget version,
![Screenshot_20200718_035318](https://user-images.githubusercontent.com/6509673/87821345-abc48500-c8aa-11ea-92b6-86d423b19bd0.png)

plasmoid version,
![Screenshot_20200718_034429](https://user-images.githubusercontent.com/6509673/87821352-acf5b200-c8aa-11ea-911f-ec3e3b6ba3b1.png)

Thanks.

**Comment by Martchus** [comment] 2020-07-17 20:20
Strange - it works for me under Plasma 5 on a 4k display. However, I've always used an integer as scaling factor so maybe that's the problem. And so far I've only tested it under Wayland because X11 doesn't support per-screen scaling. Do you use X11 or Wayland?

It is nice that you're stating the exact versions. Is this a regression compared to older versions or is the behavior of older versions unknown?

**Comment by dontdieych** [comment] 2020-07-17 20:23
X11

It is my first time install syncthingtray.

**Comment by Martchus** [comment] 2020-07-17 20:52
Ok, I'll try to reproduce this when I have time and also access to my 4k screen. In the meantime you can do some experiments as well of course, e.g. try Wayland or try different scaling factors.

**Comment by dontdieych** [comment] 2020-07-17 22:05
Thanks.

**Comment by Martchus** [comment] 2020-07-19 23:35
I can reproduce it under X11. However, it seems that there are generally some issues with the Plasma desktop and high-DPI scaling under X11 (e.g. the icon size of context menus is too small and the height of the panel isn't scaled up). So I guess there are some limitations. I'm wondering why the same QML/Qt Quick code works fine under Wayland but not under X11.

**Comment by dontdieych** [comment] 2020-07-20 03:07
Thanks.

**Comment by Martchus** [comment] 2020-07-23 16:51
I've added a potential fix but still need to test it myself. This basically just enables all of Qt's High-DPI awareness/helper¹. Not sure why the initialization of the plasmashell does not do this on its own. So I hope this fix doesn't break other parts of the plasma shell.

---
¹It enables the following settings:
```
QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling, true);
QCoreApplication::setAttribute(Qt::AA_UseHighDpiPixmaps, true);
```

**Comment by Pointedstick** [comment] 2020-07-23 16:55
See https://bugs.kde.org/show_bug.cgi?id=356446.

I'm working on it. :)

**Comment by Martchus** [comment] 2020-07-23 17:01
Thanks. I've already briefly read the issue comments as it has been mentioned in IRC. The issue has quite some history. I'm wondering what's still missing so I'm going to test it with these flags now. If it is better in overall with the High-DPI flags enabled I'll keep them and otherwise remove them again.

**Comment by dontdieych** [comment] 2020-07-23 17:11
I've added 'PLASMA_USE_QT_SCALING=1' to ~/.pam_environment.

Looks ok. Also narrower spacing problem in tray icons gone. It started as plasma 5.19 update.

**Comment by Martchus** [comment] 2020-07-26 19:17
I've tested it as well and it looks good with that environment variable (also the rest of the Plasma shell). So I'm closing this issue because it doesn't seem like there's anything left to do from my side.

By the way, the change I've made earlier apparently only has an effect within `plasmoidviewer`. Within the real `plasmashell` the settings are likely applied too late to have any effect. Considering that I doubt this issue is something a particular plasmoid can control/improve anyways.

**Closed by Martchus** 2020-07-26 19:17 UTC
Labels: bug
