### ISSUE TITLE
Crashes plasmashell (5.16.5)

### ISSUE THREAD

**Issue by RlndVt** [Martchus/syncthingtray#55] opened 2019-09-05 21:34 UTC
The combination of syncthingtray and the System Tray widget causes a crash of plasmashell (5.16.5). Also reported in the KDE tracker in case it's their end, see [1].

Worth mentioning, had to install using --nocheck [2]

[1] https://bugs.kde.org/show_bug.cgi?id=411629
[2] https://github.com/Martchus/PKGBUILDs/issues/102

**Comment by Martchus** [comment] 2019-09-05 22:24
Obviously I haven't noticed that problem so far myself.

So you're using your own build and not the one provided by my binary repo. Does my build work for you? Has your build worked before at some point (asking because you filed the other issue a few days before)? Does `syncthingtray` or `syncthingctl` work? Can it be started within plasmoidviewer or plasmawindowed? To investigate the issue you can make a debug build and run it with gdb.

**Comment by Martchus** [comment] 2019-09-05 22:28
And of course stdout/stderr would be useful as well.

**Comment by RlndVt** [comment] 2019-09-06 07:27
> Obviously I haven't noticed that problem so far myself.
> 
> So you're using your own build and not the one provided by my binary repo. Does my build work for you? 

I'd rather not add a binary source.

>Has your build worked before at some point (asking because you filed the other issue a few days before)? 

Yes with 5.16.4, since the update to .5 this has become an issue.

> Does `syncthingtray` or `syncthingctl` work? 

Haven't used syncthingctl, it seems like the combination of syncthingtray running in the System Tray causes the crash.

> Can it be started within plasmoidviewer or plasmawindowed? 

plasmoidviewer acts the same as without, starting syncthingtray with system tray open works, having syncthingtray running and then starting system tray causes a crash.

> To investigate the issue you can make a debug build and run it with gdb.

Could you elaborate?

> And of course stdout/stderr would be useful as well.

syncthingtray is silent

plasmoidviewer: 

```
QML debugging is enabled. Only use this in a safe environment.
qml: View QML loaded
invalid metadata "/usr/lib/qt/plugins/kcm_kio.so"
invalid metadata "/usr/lib/qt/plugins/kcm_trash.so"
invalid metadata "/usr/lib/qt/plugins/kcm_webshortcuts.so"
invalid metadata "/usr/lib/qt/plugins/kcm_ssl.so"
invalid metadata "/usr/lib/qt/plugins/nextclouddolphinactionplugin.so"
invalid metadata "/usr/lib/qt/plugins/kio_bluetooth.so"
invalid metadata "/usr/lib/qt/plugins/kio_obexftp.so"
invalid metadata "/usr/lib/qt/plugins/kstyle_breeze_config.so"
invalid metadata "/usr/lib/qt/plugins/kcm_filetypes.so"
invalid metadata "/usr/lib/qt/plugins/miloutextplugin.so"
invalid metadata "/usr/lib/qt/plugins/kcm_kwin_scripts.so"
invalid metadata "/usr/lib/qt/plugins/kcm_kwinoptions.so"
invalid metadata "/usr/lib/qt/plugins/kcm_kwinrules.so"
invalid metadata "/usr/lib/qt/plugins/kcm_kwinscreenedges.so"
invalid metadata "/usr/lib/qt/plugins/kcm_kwintabbox.so"
invalid metadata "/usr/lib/qt/plugins/kcm_kwintouchscreen.so"
invalid metadata "/usr/lib/qt/plugins/kwincompositing.so"
invalid metadata "/usr/lib/qt/plugins/kcm_krunner_kill.so"
invalid metadata "/usr/lib/qt/plugins/krunner_activities.so"
invalid metadata "/usr/lib/qt/plugins/krunner_appstream.so"
invalid metadata "/usr/lib/qt/plugins/krunner_bookmarksrunner.so"
invalid metadata "/usr/lib/qt/plugins/krunner_calculatorrunner.so"
invalid metadata "/usr/lib/qt/plugins/krunner_kill.so"
invalid metadata "/usr/lib/qt/plugins/krunner_locations.so"
invalid metadata "/usr/lib/qt/plugins/krunner_placesrunner.so"
invalid metadata "/usr/lib/qt/plugins/krunner_powerdevil.so"
invalid metadata "/usr/lib/qt/plugins/krunner_recentdocuments.so"
invalid metadata "/usr/lib/qt/plugins/krunner_services.so"
invalid metadata "/usr/lib/qt/plugins/krunner_sessions.so"
invalid metadata "/usr/lib/qt/plugins/krunner_shell.so"
invalid metadata "/usr/lib/qt/plugins/krunner_webshortcuts.so"
invalid metadata "/usr/lib/qt/plugins/krunner_windowedwidgets.so"
invalid metadata "/usr/lib/qt/plugins/krunner_windows.so"
invalid metadata "/usr/lib/qt/plugins/plasma-geolocation-gps.so"
invalid metadata "/usr/lib/qt/plugins/plasma-geolocation-ip.so"
invalid metadata "/usr/lib/qt/plugins/classic_mode.so"
invalid metadata "/usr/lib/qt/plugins/icon_mode.so"
invalid metadata "/usr/lib/qt/plugins/systemsettings_sidebar_mode.so"
invalid metadata "/usr/lib/qt/plugins/kcm_krunner_charrunner.so"
invalid metadata "/usr/lib/qt/plugins/kcm_krunner_dictionary.so"
invalid metadata "/usr/lib/qt/plugins/kcm_krunner_spellcheck.so"
invalid metadata "/usr/lib/qt/plugins/krunner_charrunner.so"
invalid metadata "/usr/lib/qt/plugins/krunner_converter.so"
invalid metadata "/usr/lib/qt/plugins/krunner_datetime.so"
invalid metadata "/usr/lib/qt/plugins/krunner_dictionary.so"
invalid metadata "/usr/lib/qt/plugins/krunner_katesessions.so"
invalid metadata "/usr/lib/qt/plugins/krunner_konsoleprofiles.so"
invalid metadata "/usr/lib/qt/plugins/krunner_spellcheck.so"
invalid metadata "/usr/lib/qt/plugins/kcm_kgamma.so"
invalid metadata "/usr/lib/qt/plugins/kcm_hotkeys.so"
invalid metadata "/usr/lib/qt/plugins/kcm_about_distro.so"
invalid metadata "/usr/lib/qt/plugins/kcm_devinfo.so"
invalid metadata "/usr/lib/qt/plugins/kcm_info.so"
invalid metadata "/usr/lib/qt/plugins/kcm_memory.so"
invalid metadata "/usr/lib/qt/plugins/kcm_nic.so"
invalid metadata "/usr/lib/qt/plugins/kcm_opengl.so"
invalid metadata "/usr/lib/qt/plugins/kcm_pci.so"
invalid metadata "/usr/lib/qt/plugins/kcm_samba.so"
invalid metadata "/usr/lib/qt/plugins/kcm_usb.so"
invalid metadata "/usr/lib/qt/plugins/kcm_view1394.so"
invalid metadata "/usr/lib/qt/plugins/kcm_kscreen.so"
invalid metadata "/usr/lib/qt/plugins/krunner_browsertabs.so"
invalid metadata "/usr/lib/qt/plugins/attica_kde.so"
invalid metadata "/usr/lib/qt/plugins/fontthumbnail.so"
invalid metadata "/usr/lib/qt/plugins/kcm_access.so"
invalid metadata "/usr/lib/qt/plugins/kcm_activities.so"
invalid metadata "/usr/lib/qt/plugins/kcm_autostart.so"
invalid metadata "/usr/lib/qt/plugins/kcm_baloofile.so"
invalid metadata "/usr/lib/qt/plugins/kcm_clock.so"
invalid metadata "/usr/lib/qt/plugins/kcm_componentchooser.so"
invalid metadata "/usr/lib/qt/plugins/kcm_desktoppaths.so"
invalid metadata "/usr/lib/qt/plugins/kcm_emoticons.so"
invalid metadata "/usr/lib/qt/plugins/kcm_fontinst.so"
invalid metadata "/usr/lib/qt/plugins/kcm_joystick.so"
invalid metadata "/usr/lib/qt/plugins/kcm_kded.so"
invalid metadata "/usr/lib/qt/plugins/kcm_keyboard.so"
invalid metadata "/usr/lib/qt/plugins/kcm_keys.so"
invalid metadata "/usr/lib/qt/plugins/kcm_mouse.so"
invalid metadata "/usr/lib/qt/plugins/kcm_phonon.so"
invalid metadata "/usr/lib/qt/plugins/kcm_plasmasearch.so"
invalid metadata "/usr/lib/qt/plugins/kcm_smserver.so"
invalid metadata "/usr/lib/qt/plugins/kcm_solid_actions.so"
invalid metadata "/usr/lib/qt/plugins/kcm_standard_actions.so"
invalid metadata "/usr/lib/qt/plugins/kcm_style.so"
invalid metadata "/usr/lib/qt/plugins/kcmspellchecking.so"
invalid metadata "/usr/lib/qt/plugins/kded_touchpad.so"
invalid metadata "/usr/lib/qt/plugins/kfontviewpart.so"
invalid metadata "/usr/lib/qt/plugins/kio_fonts.so"
invalid metadata "/usr/lib/qt/plugins/krunner_kwin.so"
invalid metadata "/usr/lib/qt/plugins/krunner_plasma-desktop.so"
invalid metadata "/usr/lib/qt/plugins/libkcm_device_automounter.so"
invalid metadata "/usr/lib/qt/plugins/libkcm_qtquicksettings.so"
invalid metadata "/usr/lib/qt/plugins/kcm_networkmanagement.so"
invalid metadata "/usr/lib/qt/plugins/libplasmanetworkmanagement_openconnectui.so"
invalid metadata "/usr/lib/qt/plugins/kcm_powerdevilactivitiesconfig.so"
invalid metadata "/usr/lib/qt/plugins/kcm_powerdevilglobalconfig.so"
invalid metadata "/usr/lib/qt/plugins/kcm_powerdevilprofilesconfig.so"
invalid metadata "/usr/lib/qt/plugins/powerdevilbrightnesscontrolaction_config.so"
invalid metadata "/usr/lib/qt/plugins/powerdevildimdisplayaction_config.so"
invalid metadata "/usr/lib/qt/plugins/powerdevildpmsaction.so"
invalid metadata "/usr/lib/qt/plugins/powerdevildpmsaction_config.so"
invalid metadata "/usr/lib/qt/plugins/powerdevilhandlebuttoneventsaction_config.so"
invalid metadata "/usr/lib/qt/plugins/powerdevilkeyboardbrightnesscontrolaction_config.so"
invalid metadata "/usr/lib/qt/plugins/powerdevilrunscriptaction_config.so"
invalid metadata "/usr/lib/qt/plugins/powerdevilsuspendsessionaction_config.so"
invalid metadata "/usr/lib/qt/plugins/powerdevilwirelesspowersavingaction_config.so"
invalid metadata "/usr/lib/qt/plugins/kcm_sddm.so"
invalid metadata "/usr/lib/qt/plugins/user_manager.so"
invalid metadata "/usr/lib/qt/plugins/krossmoduleforms.so"
invalid metadata "/usr/lib/qt/plugins/krossmodulekdetranslation.so"
invalid metadata "/usr/lib/qt/plugins/krossqts.so"
invalid metadata "/usr/lib/qt/plugins/akonadi_serializer_mail.so"
invalid metadata "/usr/lib/qt/plugins/kcm_mailtransport.so"
invalid metadata "/usr/lib/qt/plugins/akonadi_serializer_addressee.so"
invalid metadata "/usr/lib/qt/plugins/akonadi_serializer_contactgroup.so"
invalid metadata "/usr/lib/qt/plugins/kcm_akonadicontact_actions.so"
invalid metadata "/usr/lib/qt/plugins/akonadi_serializer_kcalcore.so"
invalid metadata "/usr/lib/qt/plugins/kcm_krunner_pimcontacts.so"
invalid metadata "/usr/lib/qt/plugins/krunner_pimcontacts.so"
invalid metadata "/usr/lib/qt/plugins/baloofilepropertiesplugin.so"
invalid metadata "/usr/lib/qt/plugins/appimagethumbnail.so"
invalid metadata "/usr/lib/qt/plugins/audiothumbnail.so"
invalid metadata "/usr/lib/qt/plugins/comicbookthumbnail.so"
invalid metadata "/usr/lib/qt/plugins/djvuthumbnail.so"
invalid metadata "/usr/lib/qt/plugins/ebookthumbnail.so"
invalid metadata "/usr/lib/qt/plugins/exrthumbnail.so"
invalid metadata "/usr/lib/qt/plugins/imagethumbnail.so"
invalid metadata "/usr/lib/qt/plugins/jpegthumbnail.so"
invalid metadata "/usr/lib/qt/plugins/kfileaudiopreview.so"
invalid metadata "/usr/lib/qt/plugins/kritathumbnail.so"
invalid metadata "/usr/lib/qt/plugins/opendocumentthumbnail.so"
invalid metadata "/usr/lib/qt/plugins/svgthumbnail.so"
invalid metadata "/usr/lib/qt/plugins/textthumbnail.so"
invalid metadata "/usr/lib/qt/plugins/windowsexethumbnail.so"
invalid metadata "/usr/lib/qt/plugins/windowsimagethumbnail.so"
invalid metadata "/usr/lib/qt/plugins/dolphinpart.so"
invalid metadata "/usr/lib/qt/plugins/kcm_dolphingeneral.so"
invalid metadata "/usr/lib/qt/plugins/kcm_dolphinnavigation.so"
invalid metadata "/usr/lib/qt/plugins/kcm_dolphinservices.so"
invalid metadata "/usr/lib/qt/plugins/kcm_dolphinviewmodes.so"
invalid metadata "/usr/lib/qt/plugins/fileviewbazaarplugin.so"
invalid metadata "/usr/lib/qt/plugins/fileviewdropboxplugin.so"
invalid metadata "/usr/lib/qt/plugins/fileviewgitplugin.so"
invalid metadata "/usr/lib/qt/plugins/fileviewhgplugin.so"
invalid metadata "/usr/lib/qt/plugins/fileviewsvnplugin.so"
invalid metadata "/usr/lib/qt/plugins/gvpart.so"
invalid metadata "/usr/lib/qt/plugins/akonadi_serializer_kalarm.so"
invalid metadata "/usr/lib/qt/plugins/kcm_knote.so"
invalid metadata "/usr/lib/qt/plugins/kcm_knotessummary.so"
invalid metadata "/usr/lib/qt/plugins/kontact_knotesplugin.so"
invalid metadata "/usr/lib/qt/plugins/kcm_kwallet5.so"
invalid metadata "/usr/lib/qt/plugins/kio_msits.so"
invalid metadata "/usr/lib/qt/plugins/okularpart.so"
invalid metadata "/usr/lib/qt/plugins/libsyncthingfileitemaction.so"
org.kde.plasmaquick: Applet preload policy set to 1
Toolbox not loading, toolbox package is either invalid or disabled.
file:///usr/share/plasma/wallpapers/org.kde.image/contents/ui/main.qml:71:9: Unable to assign [undefined] to QStringList
file:///usr/share/plasma/wallpapers/org.kde.image/contents/ui/main.qml:71:9: Unable to assign [undefined] to QStringList
qml: New Containment: ContainmentInterface(0x55a084b9ec70)
org.kde.plasma.notifications: Failed to register Notification service on DBus
org.kde.plasma.notifications: Failed to register JobViewServer service on DBus, is kuiserver running?
org.kde.plasma.notifications: Failed to register JobViewServer DBus object
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
Both point size and pixel size set. Using pixel size.
free(): invalid pointer
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = plasmoidviewer path = /usr/bin pid = 17299
KCrash: Arguments: /usr/bin/plasmoidviewer -a org.kde.plasma.systemtray 
KCrash: Attempting to start /usr/lib/drkonqi from kdeinit
QSocketNotifier: Invalid socket 7 and type 'Read', disabling...
QSocketNotifier: Invalid socket 16 and type 'Read', disabling...
QSocketNotifier: Invalid socket 22 and type 'Read', disabling...
QSocketNotifier: Invalid socket 23 and type 'Read', disabling...
QSocketNotifier: Invalid socket 28 and type 'Read', disabling...
QSocketNotifier: Invalid socket 29 and type 'Read', disabling...
QSocketNotifier: Invalid socket 30 and type 'Read', disabling...
QSocketNotifier: Invalid socket 25 and type 'Read', disabling...
Unable to start Dr. Konqi
Re-raising signal for core dump handling.
```

**Comment by Martchus** [comment] 2019-09-06 08:44
> it seems like the combination of syncthingtray running in the System Tray causes the crash.

I thought this issue is about the *Plasmoid* (and not the standalone `syncthingtray` application). Is this about the *Plasmoid* (`libsyncthingplasmoid.so`) or `syncthingtray`?

> Could you elaborate?

See the "building this straight" section in the build instructions and use `-DCMAKE_BUILD_TYPE=Debug`. But let's clarify what the issue is about first.

> Yes with 5.16.4, since the update to .5 this has become an issue.

This is good to know. I guess I haven't been using .5 so far. Maybe I can just reproduce it myself using that version (have no time right now). Then it might be a Plasma bug, indeed.

**Comment by herrwusel** [comment] 2019-09-06 10:02
Syncthingtray and the plasmoid is running fine for me:
![2019-09-06_12-00](https://user-images.githubusercontent.com/8242787/64419895-33900f00-d09e-11e9-98f4-458a650b40a0.png)

**Comment by Martchus** [comment] 2019-09-06 20:08
I've just updated to 5.16.5 and I can not reproduce it, too. Regardless whether this is about the standalone version or the Plasmoid. I also tested showing the Plasmoid within the system tray Plasmoid and adding it as extra Plasmoid.

**Comment by rulatir** [comment] 2019-10-17 10:10
I notice a weird meta-anomaly: this "invalid metadata" error message, typically occurring in dozens or hundreds, is being reported right end left in the context of plasmashell crashing and doing other weird things, but no one seems to investigate OR be able to give ANY explanation as to what this symptom really means. Whenever these "invalid metadata" errors are reported, the discussion IMMEDIATELY shifts to something else. This is really, really, really weird.

I mean, these words, "invalid metadata", which form part of the error message - they were typed by a human being in a specific place in code. That human being might know what is going on, or at least provide hints towards the underlying cause. Who is that human being? Where is that place in code? Why does no-one investigate the symptom?

**Comment by Martchus** [comment] 2019-10-17 11:21
Unfortunately I don't know the answer to most of these questions. I'm also not a plasma developer myself.

> Where is that place in code?

Maybe `git grep` can help.

> Who is that human being?

Maybe `git blame` can help.

> Why does no-one investigate the symptom?

I presume that these errors are likely caused by an invalid installation/distribution of these plugins. The error messages themselves speak for that and the fact that not a lot of users can reproduce it (here only @RlndVt could reproduce it). So if it is really just an installation/distribution issue the only thing developers could do to improve is making the error message more verbose so users would at least know what in particular is wrong with the meta-data and what's possibly missing.

Note that I have not ignored the issue but I simply don't know how to help. Maybe the same is true for the plasma developers as well. (Although an improved error message would likely help.)

**Comment by PotcFdk** [comment] 2020-02-10 10:11
I just wanted to try out syncthingtray myself for the first time and after logging out and in again, I can briefly see some kind of syncthingtray related notification. Then, plasmashell crashes.
So in case it was not already known - there are apparently at least two users who experience this, now.

**Comment by PotcFdk** [comment] 2020-02-10 10:17
In case it matters, the notification says
```
Syncthing Tray

Syncthing Tray - internal error
Connection configuration is insufficient.
```

**Comment by Martchus** [comment] 2020-02-10 10:28
Are you using the stand-alone Qt Widgets based `syncthingtray` application (1) or are you using the Plasmoid (2)? Beside that I also need at least a little bit more information. Logs of `plasmashell` and `syncthingtray` (if 1) and a stack trace would be useful. And how did you build and install it? Which version of Syncthing Tray / Plasma / Qt are you using? If (1), does the AppImage linked in the README work?

The notification itself just means that you have to open the settings to configure how it should connect to Syncthing.

**Comment by PotcFdk** [comment] 2020-02-11 16:28
Tested on Plasma 5.17.5-2 / Qt 5.14.1-1.
I observed something new today:
After reinstalling the package again (`$ pikaur -S syncthingtray`), I immediately (without logging out/rebooting) ran `syncthingtray` in a terminal, which didn't crash me and instead displayed the GUI just fine.
I stopped that process, right-clicked a Panel and went through "Add Widgets..." to find the Syncthing widget (I assume this is the Plasmoid?) and added it to my tray bar.
I logged out and in again and saw two Syncthing icons - one was the widget, and one was inside the system tray. **Plasma didn't crash.**
Then I proceeded to remove the widget again, and I was left with only the system tray icon and a still-running Plasma. After logging out and in again, it went back to auto-crashing after the login.

A relevant entry in the journalctl would be
```
Feb 11 17:19:03 HOSTNAME systemd-coredump[18784]: Process 18769 (plasmashell) of user 1000 dumped core.
                                                 
                                                 Stack trace of thread 18769:
                                                 #0  0x00007fc2b0919f25 raise (libc.so.6 + 0x3bf25)
                                                 #1  0x00007fc2b0903897 abort (libc.so.6 + 0x25897)
                                                 #2  0x00007fc2b095d258 __libc_message (libc.so.6 + 0x7f258)
                                                 #3  0x00007fc2b096477a malloc_printerr (libc.so.6 + 0x8677a)
                                                 #4  0x00007fc2b096614c _int_free (libc.so.6 + 0x8814c)
                                                 #5  0x00007fc2b0f64000 _ZN7QObject5eventEP6QEvent (libQt5Core.so.5 + 0x2d3000)
                                                 #6  0x00007fc2b1b55362 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x15b362)
                                                 #7  0x00007fc2b1b5e819 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x164819)
                                                 #8  0x00007fc2b0f36962 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2a5962)
                                                 #9  0x00007fc2b0f391c6 _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt5Core.so.5 + 0x2a81c6)
                                                 #10 0x00007fc2b0f8f9d4 n/a (libQt5Core.so.5 + 0x2fe9d4)
                                                 #11 0x00007fc2af27139e g_main_context_dispatch (libglib-2.0.so.0 + 0x6a39e)
                                                 #12 0x00007fc2af2731b1 n/a (libglib-2.0.so.0 + 0x6c1b1)
                                                 #13 0x00007fc2af2731f1 g_main_context_iteration (libglib-2.0.so.0 + 0x6c1f1)
                                                 #14 0x00007fc2b0f8f020 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2fe020)
                                                 #15 0x00007fc2b0f354cc _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a44cc)
                                                 #16 0x00007fc2b0f3d4d6 _ZN16QCoreApplication4execEv (libQt5Core.so.5 + 0x2ac4d6)
                                                 #17 0x000055c6608c0dc9 n/a (plasmashell + 0x1cdc9)
                                                 #18 0x00007fc2b0905153 __libc_start_main (libc.so.6 + 0x27153)
                                                 #19 0x000055c6608c122e _start (plasmashell + 0x1d22e)
                                                 
                                                 Stack trace of thread 18777:
                                                 #0  0x00007fc2b09d29ef __poll (libc.so.6 + 0xf49ef)
                                                 #1  0x00007fc2af273120 n/a (libglib-2.0.so.0 + 0x6c120)
                                                 #2  0x00007fc2af2731f1 g_main_context_iteration (libglib-2.0.so.0 + 0x6c1f1)
                                                 #3  0x00007fc2b0f8f020 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2fe020)
                                                 #4  0x00007fc2b0f354cc _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a44cc)
                                                 #5  0x00007fc2b0d59e52 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc8e52)
                                                 #6  0x00007fc2b29f7eab n/a (libQt5Quick.so.5 + 0x14eeab)
                                                 #7  0x00007fc2b0d5afc6 n/a (libQt5Core.so.5 + 0xc9fc6)
                                                 #8  0x00007fc2b01954cf start_thread (libpthread.so.0 + 0x94cf)
                                                 #9  0x00007fc2b09dd2d3 __clone (libc.so.6 + 0xff2d3)

[... more thread stacks ...]
```

**Comment by Martchus** [comment] 2020-02-12 09:52
> I assume this is the Plasmoid?

Yes. That's at least how they call it in [some tutorials](https://techbase.kde.org/Development/Tutorials/Plasma5). Sometimes they also call them ["applets"](https://api.kde.org/frameworks/plasma-framework/html/classPlasma_1_1Applet.html) and in the UI they use a term which I'd translate to "mini programs" (from German).

---

You're saying that you've removed the Plasmoid again before restarting. That means *no* code from this repository ran at the time within the `plasmashell` process. The trace also indicates that the crash doesn't happen immediately in one of my libraries.

> After logging out and in again, it went back to auto-crashing after the login.

So you enabled the autostart feature of `syncthingtray` (1)? Or did you start `syncthingtray` manually (2) or did you add the Plasmoid again (3)? I am asking because you still haven't communicated whether the crash happens with `syncthingtray` or the Plasmoid. (In the last comment you've mentioned both but none lead to a crash until restarting `plasmashell`.)

By the way, if it is (1) or (2) which means you were using `syncthingtray` the fault is quite likely on the `plasmashell` side.

It would also be useful to have the log of `plasmashell`. If you start the shell from a terminal you will see its output. (You need terminate the currently running `plasmashell` process before doing that.)

**Comment by Martchus** [comment] 2020-03-01 19:47
I've just found one bug in qtutilities which causes random crashes producing a similar stack trace. It will be fixed in the next qtutilities release, see https://github.com/Martchus/qtutilities/commit/4ce6bb948747395028cda56e4e6c3aa5690d1423

**Comment by PotcFdk** [comment] 2020-04-27 21:36
Seems to be fixed for me.

**Comment by Martchus** [comment] 2020-04-27 21:57
The bug I've found in qtutilities was very likely it so I'm closing the issue. Feel free to re-open if the issue is still present with the latest version of c++utilities/qtutilities/syncthingtray and the stack trace is the same.

**Closed by Martchus** 2020-04-27 21:57 UTC
Labels: bug
