### ISSUE TITLE
syncthingctl wait-for-idle for disconnected devices

### ISSUE THREAD

**Issue by CaseOf** [Martchus/syncthingtray#199] opened 2023-08-25 18:19 UTC
**Relevant components**
* [ ] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [x] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [x] Backend libraries

**Is your feature request specific to a certain platform/environment? Please specify.**
No

**Is your feature request related to a problem? Please describe.**
When running `syncthingctl -w --dev [device-id-here]` it does not consider to still wait for device to be online.

**Describe the solution you'd like**
I would like `wait-for-idle` feature in `syncthingctl` to wait for a given device via `--dev` to be online and synced to trigger it being idle.

**Describe alternatives you've considered**

**Additional context**
When device is offline, I cannot guarantee sync is up to date on both devices.
On my context, it is to wait all data to be synced to start a backup via borg on a script.

**Comment by Martchus** [comment] 2023-08-26 22:13
The change https://github.com/Martchus/syncthingtray/commit/89caa7610287860c2661b0c663ef7d57dbe83f6d that I have committed on master should do the trick. It is a failry simple change so I assume it works. However, I haven't tested it yet. You might want to test it yourself by building from the master branch.

**Comment by CaseOf** [comment] 2023-08-27 16:18
I did try from master, it is still ending the wait instantly on a disconnected device.

**Comment by Martchus** [comment] 2023-08-27 20:03
A stupid question, but have you actually used the newly introduced option `--require-devs-connected`? I did not change the default behavior because that would probably be an incompatible change.

I guess I'll be able to test this myself tomorrow.

**Comment by CaseOf** [comment] 2023-08-27 23:44
> A stupid question, but have you actually used the newly introduced option `--require-devs-connected`? I did not change the default behavior because that would probably be an incompatible change.

Not that stupid, I did not try it before you mentioned it even if I did see it in your code  ¯\_(ツ)_/¯
Now that I’m using it on master, the behavior is what I did expect in my scenario, so it is working!

**Comment by CaseOf** [comment] 2023-08-27 23:51
Maybe a trigger once device comes back online?

**Comment by Martchus** [comment] 2023-08-28 00:36
> Now that I’m using it on master, it is waiting while the device is disconnected but still waits once device connects, sync, and then idle.

You mean the CLI never stops waiting even if the device is connected and idling at some point? Not sure why it would get stuck this way. I suppose I need to debug this myself then.

**Comment by CaseOf** [comment] 2023-08-29 18:05
> > Now that I’m using it on master, it is waiting while the device is disconnected but still waits once device connects, sync, and then idle.
> 
> You mean the CLI never stops waiting even if the device is connected and idling at some point? Not sure why it would get stuck this way. I suppose I need to debug this myself then.

that's what I meant

**Comment by Martchus** [comment] 2023-09-01 21:42
I tested it myself and could reproduce the issue. There was nothing wrong with my change but there was something more fundamentally broken in the way device events are processed in the underlying library. It should be fixed on master so you might want to test it again yourself.

**Comment by CaseOf** [comment] 2023-09-02 22:27
It seems to work as expected now. Thanks !

**Closed** 2023-09-03 07:09 UTC
Labels: feature  request
