### ISSUE TITLE
Web view on Windows

### ISSUE THREAD

**Issue by RuiNtD** [Martchus/syncthingtray#178] opened 2023-03-25 22:39 UTC
**Relevant components**
* [X] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Is your feature request specific to a certain platform/environment? Please specify.**
Windows

**Is your feature request related to a problem? Please describe.**
It would be nice to be able to access the web UI on Windows without opening my browser.

**Describe the solution you'd like**
Web view support on Windows

**Describe alternatives you've considered**
🤔 

**Additional context**

**Comment by Martchus** [comment] 2023-03-25 22:49
This should already work. Note that binaries provided by myself on GitHub don't have the web UI enabled because I am reluctant to ship a web browser.

Any third party is welcome to provide such builds. I will nevertheless close the issue for now as it is nothing I will work on. If someone likes to work on it, please you can leave a comment and I'll reopen the issue.

**Comment by Martchus** [comment] 2023-03-25 22:54
Note that if Qt WebView gains support for using Window's native web rendering facilities I will implement support for utilizing it and enable it in my Windows build. However, to my knowledge this is not possible yet.

**Comment by RuiNtD** [comment] 2023-03-26 15:15
Any chance an option could be added instead to open the web UI in Chrome / Edge app mode?
```console
msedge -app="http://localhost:8384"
```

**Comment by Martchus** [comment] 2023-03-26 15:53
I haven't had that idea yet. That's something that would be easy to implement, one just has to do it. Maybe it is even possible to pass auth credentials this way.

Maybe I'll do it at some point so I'll reopen the issue.

**Comment by Martchus** [comment] 2023-03-26 21:13
I've just tried `/c/Program\ Files\ \(x86\)/Microsoft/Edge/Application/msedge --app="http://localhost:8384"`` and it looks really good. Definitely better than shipping a complete browser stack (as it was required for Qt WebEngine). It will still be a bit of work to implement:

* The path of Edge needs to be located dynamically. Supposedly one can read it somewhere from the registry and fall back to some common location.
* The process should preferrably be be tracked so when one opens Syncthing when it is already open the existing window is simply focused.
* Passing auth credentials is a nice feature provided by the built-in web view. It would be great it could be passed to Edge as well. Unfortunately it doesn't seem to support passing credentials via the URL.
* Another feature of the built-in web view is validation of the self-signed certificate if TLS is enabled. Supposedly this is not possible but one could at least specify `--allow-insecure-localhost` to be able to at least access the page (without validation).

Alternatively, one could also try to use https://learn.microsoft.com/en-us/microsoft-edge/webview2 directly, even though Qt doesn't support it. According to https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/overview-features-apis?tabs=dotnetcsharp there are APIs to deal with authentication.

**Comment by RuiNtD** [comment] 2023-03-26 22:39
> The path of Edge needs to be located dynamically. Supposedly one can read it somewhere from the registry and fall back to some common location.
I mean, considering it's pre-installed on Windows 10 and 11, install location should be consistent. Even then, the executable could be customizable; since the same flags should work on any Chromium based browser.

**Comment by RuiNtD** [comment] 2023-03-27 15:53
I also found this reference online for registry values that point to MS Edge:
![](https://www.tenforums.com/attachments/browsers-email/329628d1619486391t-edge-executable-file-location-registry-registry-seek.jpg)
Source: https://www.tenforums.com/browsers-email/178354-edge-executable-file-location-registry.html

I feel like `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\msedge.exe` would be the most reliable registry value to check for MS Edge. You could also fall back to `chrome.exe` if Edge has been (forcefully) uninstalled, which can be located in registry with a similar key.

**Comment by Martchus** [comment] 2023-03-27 18:33
I've created a first commit (58b8a4e5403ddae8ef0c5fc1bf6a90b625ec110e) to support this feature in general. At this point it just tries to locate `chromium` in path but you can override the executable via `SYNCTHINGWIDGETS_CHROMIUM_BASED_BROWSER`. I've only tested it under GNU/Linux with Chromium itself so far but it should work under Windows as well if you set the mentioned environment variable to the path of Edge.

The next step would be a better automatic detection and the possibility to override the command-line from the UI.

**Comment by Martchus** [comment] 2023-03-27 22:12
Tested it on Windows with `SYNCTHINGWIDGETS_CHROMIUM_BASED_BROWSER=C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe` for my system and it works just fine.

Just for the sake of it, I've also tested whether the web view using Qt WebEngine works and it works as well. However, it was really slow. For instance the animations of Syncthing's UI were not fluent at all. Maybe it is because I've been using a debug build of Qt (the official MSVC build).

**Comment by Martchus** [comment] 2023-03-28 20:37
With https://github.com/Martchus/syncthingtray/commit/033cd21d839380b8a2b396ec821f4fe8c5dfcf72 the automatic detection should be good enough. Being able to select a binary manually is still missing.

Note sure whether I'll look also into the other ideas mentioned in https://github.com/Martchus/syncthingtray/issues/178#issuecomment-1484225906 as they are more effort to implement and maybe not even possible besides focusing an already opened window.

**Comment by RuiNtD** [comment] 2023-03-28 22:14
BTW, it might be a good idea to add `brave.exe` to the list. c:

**Comment by Martchus** [comment] 2023-03-31 21:00
I've been adding a way to configure a custom command via the UI.

One could also add Vivaldi. However, I would actually add none of them because this also needs testing - and I'm not willing to regularly test a bunch of browsers. I've been adding Edge to the list because it should be installed by default on Windows and I've added Chromium/Chrome to the list because it is very likely installed on Windows and GNU/Linux. Those two should suffice. If one wants to use a different browser this is now easily possible and the extra configuration step makes it also clear that one leaves the realm of supported configurations.

**Comment by RuiNtD** [comment] 2023-04-05 20:49
Trying out Web View on 1.4.0, and it doesn't save the setting across restarts.

**Comment by Martchus** [comment] 2023-04-05 22:13
Right, I can reproduce the problem. I suspect it only happens with builds where built-in web view support is disabled as I have tested this actually a lot with builds with built-in web view support enabled.

**Comment by Martchus** [comment] 2023-04-07 00:11
Fixed in 1.4.1.

**Closed by Martchus** 2023-04-07 00:11 UTC
Labels: feature  request
