### ISSUE TITLE
Syncthing Tray ignores .ini file next to exe when launching through CMD or bat file

### ISSUE THREAD

**Issue by cavalrymargarine0x1** [Martchus/syncthingtray#298] opened 2024-11-21 23:46 UTC
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)

**Environment and versions**
* Versions of `syncthingtray`, `qtutilities` and `c++utilities`: SyncthingTray 1.6.3
* Qt version: N/A 
* C++ compiler (name and version): N/A
* C++ standard library (name and version): N/A
* Operating system (name and version): Windows 10 Pro 

**Bug description**
Syncthing Tray ignores syncthingtray.ini file next to exe when launching through CMD or bat file, acting as if it was the first time launching it.

**Steps to reproduce**
1. Download SyncthingTray
2. Unzip it to a folder
3. Open it, make a few changes to the config
4. Move syncthingtray.ini from `%appdata%\syncthingtray.ini` to SyncthingTray.exe's folder
5. Launch SyncthingTray through CMD or a bat file (`[PathToSyncthingTrayExeFolder]\SyncthingTray.exe`)
6. See that SyncthingTray acts as if it was the first time launching it, ignoring the syncthingtray.ini file placed in its folder

**Expected behavior**
SyncthingTray launches as if it were the first time, ignoring the syncthingtray.ini file placed in the SyncthingTray.exe folder and creating a new one in `%appdata%`

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Martchus** [comment] 2024-11-22 00:05
This issue is probably a duplicate of https://github.com/Martchus/syncthingtray/issues/295 so I'm closing it. You can try the executable linked in the other issue. If it doesn't work and those are distinct issues you can reopen.

**Closed by Martchus** 2024-11-22 00:05 UTC
Labels: bug
