### ISSUE TITLE
[Linux] libboost_filesystem.so.1.75.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Willie30F** [Martchus/syncthingtray#103] opened 2021-07-30 08:49 UTC
**Relevant components**
* [X] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* Versions of `syncthingtray`, `boost-libs`: 1.1.8-1, 1.76.0-1
* Qt version: 5.15.2
* Operating system (name and version): Manjaro (arch) Linux

**Bug description**
I notices that syncthingtray won't start anymore when starting my operating system. I then tried to start it via the console window to see whats wrong. It searches for libboost_filesystem.so.1.75.0 which it can't find because I a newer version got installed with the latest update of syncthingtray.

```
❯ syncthingtray
syncthingtray: error while loading shared libraries: libboost_filesystem.so.1.75.0: cannot open shared object file: No such file or directory
```

Heres a locate command searching for the requested library, the problem might be the version that's put in the actual filename of the library:
```
❯ locate libboost_filesystem
/usr/lib/libboost_filesystem.a
/usr/lib/libboost_filesystem.so
/usr/lib/libboost_filesystem.so.1.76.0
/usr/lib/cmake/boost_filesystem-1.76.0/libboost_filesystem-variant-shared.cmake
/usr/lib/cmake/boost_filesystem-1.76.0/libboost_filesystem-variant-static.cmake
```

**Expected behavior**
To start normally using the library without the version number, which you can see in my locate search above. I guess that's a link to the actual library just without the version number in it.

Anymore questions? Just ask please :)

**Comment by Martchus** [comment] 2021-07-30 08:51
Not a bug, duplicate of https://github.com/Martchus/syncthingtray/issues/98

**Closed by Martchus** 2021-07-30 08:51 UTC
Labels: invalid

**Comment by Willie30F** [comment] 2021-07-30 08:53
Oh, thanks, didn't find this one for whatever reason, actually searched for boost 😮
