### ISSUE TITLE
Does not build on arch

### ISSUE THREAD

**Issue by rumpelsepp** [Martchus/syncthingtray#1] opened 2016-10-31 08:29 UTC
Some cmake magic is happening.

```
==> Starting build()...
-- Linking syncthingconnector dynamically against c++utilities (c++utilities).
-- Adding c++utilities.a  to static library dependencies of syncthingconnector.
-- Using default CXX11 ABI (not forcing old CX11 ABI).
-- Linking syncthingconnector dynamically against Qt 5.
-- Project has translations which will be released.
-- Using template for Config.cmake from CPP_UTILITIES installation.
-- Using template for global.h from CPP_UTILITIES installation.
-- Using template for template.pc from CPP_UTILITIES installation.
-- Using template for doxygen from CPP_UTILITIES installation.
-- Generating target for generating API documentation for syncthingconnector with Doxygen
-- Using template for config.h from CPP_UTILITIES installation.
-- Linking syncthingctl dynamically against c++utilities (c++utilities).
-- Adding c++utilities.a  to static library dependencies of syncthingctl.
-- Linking syncthingctl dynamically against syncthingconnector (syncthingconnector).
-- Adding syncthingconnector.a  to static library dependencies of syncthingctl.
-- Using default CXX11 ABI (not forcing old CX11 ABI).
-- Linking syncthingctl dynamically against Qt 5.
-- Using template for desktop from CPP_UTILITIES installation.
-- Using template for bash-completion.sh from CPP_UTILITIES installation.
-- Generating files for bash completion.
-- Using template for doxygen from CPP_UTILITIES installation.
-- Generating target for generating API documentation for syncthingctl with Doxygen
-- Using template for config.h from CPP_UTILITIES installation.
-- Linking syncthingmodel dynamically against c++utilities (c++utilities).
-- Adding c++utilities.a  to static library dependencies of syncthingmodel.
-- Linking syncthingmodel dynamically against syncthingconnector (syncthingconnector).
-- Adding syncthingconnector.a  to static library dependencies of syncthingmodel.
-- Using default CXX11 ABI (not forcing old CX11 ABI).
-- Linking syncthingmodel dynamically against Qt 5.
-- Project has translations which will be released.
-- Using template for Config.cmake from CPP_UTILITIES installation.
-- Using template for global.h from CPP_UTILITIES installation.
-- Using template for template.pc from CPP_UTILITIES installation.
-- Using template for doxygen from CPP_UTILITIES installation.
-- Generating target for generating API documentation for syncthingmodel with Doxygen
-- Using template for config.h from CPP_UTILITIES installation.
-- Linking syncthingtray dynamically against c++utilities (c++utilities).
-- Adding c++utilities.a  to static library dependencies of syncthingtray.
CMake Error at tray/CMakeLists.txt:112 (find_package):
  Could not find a configuration file for package "qtutilities" that is
  compatible with requested version "5.1.0".

  The following configuration files were considered but not accepted:

    /usr/share/qtutilities/cmake/qtutilitiesConfig.cmake, version: 5.0.0
    /usr/share/qtutilities/cmake/qtutilitiesConfig.cmake, version: 5.0.0



-- Configuring incomplete, errors occurred!
See also "/tmp/makepkg/syncthingtray/src/syncthingtray-0.0.3/CMakeFiles/CMakeOutput.log".
==> ERROR: A failure occurred in build().
    Aborting...
:: failed to build syncthingtray package(s)
```

**Comment by Martchus** [comment] 2016-10-31 08:45
I forgot to update the qtutilities package in the AUR. Should work now (you will have to rebuild qtutilities).

**Comment by Martchus** [comment] 2016-11-02 20:08
I assume the issue is fixed now. If not, just reopen it.

**Closed by Martchus** 2016-11-02 20:08 UTC
Labels: bug

**Comment by rumpelsepp** [comment] 2016-11-03 08:51
Oh yeah... I missed doing an answer. Yes it works, thank you. :)
