### ISSUE TITLE
Wrong UI layout on KDE Plasma

### ISSUE THREAD

**Issue by mrpink17** [Martchus/syncthingtray#120] opened 2021-11-20 23:07 UTC
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [x] Plasmoid/applet for Plasma desktop

**Environment and versions**
* syncthingtray 1.1.12-1
* qtutilities 6.5.2-1 
* c++utilities 5.11.3-1
* Qt Version: 5.15.2
* C++ compiler (name and version): gcc version 11.1.0
* C++ standard library (name and version): glibc 2.33-5
* Operating System: Arch Linux
* KDE Plasma Version: 5.23.3
* KDE Frameworks Version: 5.88.0

**Bug description**
The toolbar buttons are missing.  Pause and Stop buttons have only text and are not clickable.

**Steps to reproduce**
Click the tray icon

**Screenshots**
![Screenshot_20211120_235206](https://user-images.githubusercontent.com/13852200/142743374-3d10b053-716d-43af-a9ba-52bb91d6b444.png)

**Comment by Martchus** [comment] 2021-11-21 22:41
I'm aware that the current release is quite broken - however, in my plasma shell it doesn't look *that* broken. Can you test against the current master? Maybe it fixes the breakage in your case as well.

**Comment by kd8bny** [comment] 2021-11-22 13:57
Confirmed, the git version fixes all the issues.

**Comment by Martchus** [comment] 2021-11-22 14:14
The clipping issue is likely https://github.com/Martchus/syncthingtray/issues/65. So I cannot do much about it when the Plasmoid is displayed as part of the system tray Plasmoid.

Note that the Plasmoid deserves a complete overhaul to be more in-line with official Plasmoids anyways. Then I'd likely move most of the buttons inside the usual hamburger menu so less horizontal space is required. The "side-tabs" are now also no longer used by any official Plasmoids and should likely be replaced by regular tabs. That would also save some horizontal space.

**Comment by kd8bny** [comment] 2021-11-22 16:56
ah cool beans, saw that on the README as well.
I went with the separate plasmid for now, works fine.
Thanks!

**Comment by Martchus** [comment] 2021-11-30 18:46
I gave the Plasmoid a bit of a rework as stated in the previous comment. Also see https://github.com/Martchus/syncthingtray/issues/65#issuecomment-982916337.

**Comment by Martchus** [comment] 2022-02-08 11:46
I'm closing this because due to the rework the issue should be fixed and #65 (for possible clipping) is still open.

**Closed by Martchus** 2022-02-08 11:46 UTC
Labels: bug
